version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.295
    container_name: jenkins
    hostname: jenkins
    restart: always
    user: root
    ports:
      - 7000:8080
      - 50000:50000
    volumes:
      - /james/jenkins/data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "JAVA_OPTS=-Duser.timezone=GMT+08"