services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: postgres