version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    shm_size: 512mb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uNf6PCECa7yrfGVa
      POSTGRES_DB: test