version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    volumes:
      - ./logs:/home/nacos/logs
      - ./data:/home/nacos/data
    environment:
      - "NACOS_SERVERS=192.168.1.1:8848 192.168.1.2:8848 192.168.1.3:8848"
      - "NACOS_SERVER_IP=192.168.1.1"
      - "NACOS_SERVER_PORT=8848"
      - "JVM_XMS=2g"
      - "JVM_XMX=2g"
      - "JVM_XMN=1g"
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: always