version: '3'
services:
  kafka:
    image: bitnami/kafka:3
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - ./data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=172.16.211.154:2181,172.16.211.155:2181,172.16.211.156:2181
      - ALLOW_PLAINTEXT_LISTENER=yes