version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    external_links:
      - es01:elasticsearch
    ports:
      - 5601:5601
    networks:
      - dev
      
networks:
  dev:
    driver: bridge