version: '3'
services:
  rabbit:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - dev
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_USER=james"
      - "RABBITMQ_DEFAULT_PASS=James2020+"

networks:
  dev:
    external: true
