services:
  mysql:
    image: mysql:8
    restart: always
    hostname: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/my.cnf:ro
      - ./data:/var/lib/mysql
