services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - dev
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db/
      - ./setup:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: shiduai
      MONGO_INITDB_ROOT_PASSWORD: ShiDuAI2020+
    command: mongod --auth

networks:
  dev:
    external: true
